import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { 
  SparklesIcon, 
  CpuChipIcon, 
  HeartIcon,
  ChartBarIcon
} from '@heroicons/react/24/outline';

const LandingPage = () => {
  const features = [
    {
      icon: SparklesIcon,
      title: 'AI-Powered Planning',
      description: 'Get personalized meal plans generated by advanced AI based on your ingredients and preferences.'
    },
    {
      icon: CpuChipIcon,
      title: 'Smart Recipe Matching',
      description: 'Input your available ingredients and discover perfect recipes that maximize what you have.'
    },
    {
      icon: HeartIcon,
      title: 'Dietary Preferences',
      description: 'Support for vegan, vegetarian, keto, gluten-free, and many more dietary requirements.'
    },
    {
      icon: ChartBarIcon,
      title: 'Nutrition Tracking',
      description: 'Monitor your nutritional intake with detailed breakdowns and goal tracking.'
    }
  ];

  return (
    <div className="overflow-hidden">
      {/* Hero Section */}
      <section className="relative min-h-screen flex items-center hero-gradient">
        <div className="container-custom relative z-10">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.8 }}
            className="text-center space-y-8 max-w-4xl mx-auto"
          >
            {/* Badge */}
            <div className="inline-flex items-center space-x-2 bg-primary-500/10 border border-primary-500/20 rounded-full px-4 py-2">
              <SparklesIcon className="w-4 h-4 text-primary-400" />
              <span className="text-primary-400 text-sm font-medium">
                AI-Powered Meal Planning
              </span>
            </div>

            {/* Main heading */}
            <div className="space-y-6">
              <h1 className="text-5xl md:text-6xl lg:text-7xl font-bold leading-tight">
                <span className="text-gradient">Smart Meal Planning</span>
                <br />
                <span className="text-white">Powered by AI</span>
              </h1>
              <p className="text-xl lg:text-2xl text-dark-300 leading-relaxed max-w-3xl mx-auto">
                Transform your available ingredients into personalized meal plans with 
                AI-powered recipe suggestions and nutrition tracking.
              </p>
            </div>

            {/* CTA Buttons */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ delay: 0.4 }}
              className="flex flex-col sm:flex-row gap-4 justify-center"
            >
              <Link 
                to="/register" 
                className="btn-primary text-lg px-8 py-4 hover-glow"
              >
                Start Planning Free
              </Link>
              <Link 
                to="/recipes" 
                className="btn-secondary text-lg px-8 py-4"
              >
                Browse Recipes
              </Link>
            </motion.div>

            {/* Stats */}
            <div className="flex items-center justify-center space-x-8 pt-8">
              <div className="text-center">
                <div className="text-2xl font-bold text-primary-400">10K+</div>
                <div className="text-sm text-dark-400">Recipes</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-secondary-400">5K+</div>
                <div className="text-sm text-dark-400">Users</div>
              </div>
              <div className="text-center">
                <div className="text-2xl font-bold text-primary-400">100K+</div>
                <div className="text-sm text-dark-400">Meal Plans</div>
              </div>
            </div>
          </motion.div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-20 bg-dark-900/50">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="text-center mb-16"
          >
            <h2 className="text-4xl font-bold text-gradient mb-4">
              Everything you need for smart meal planning
            </h2>
            <p className="text-xl text-dark-300 max-w-2xl mx-auto">
              Discover how AI can revolutionize your approach to nutrition and meal preparation
            </p>
          </motion.div>

          <div className="grid md:grid-cols-2 lg:grid-cols-4 gap-8">
            {features.map((feature, index) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, y: 20 }}
                whileInView={{ opacity: 1, y: 0 }}
                transition={{ duration: 0.6, delay: index * 0.1 }}
                className="card p-6 hover-lift space-y-4"
              >
                <div className="w-12 h-12 bg-primary-500/10 rounded-lg flex items-center justify-center">
                  <feature.icon className="w-6 h-6 text-primary-400" />
                </div>
                <h3 className="text-xl font-semibold text-white">{feature.title}</h3>
                <p className="text-dark-300">{feature.description}</p>
              </motion.div>
            ))}
          </div>
        </div>
      </section>

      {/* CTA Section */}
      <section className="py-20">
        <div className="container-custom">
          <motion.div
            initial={{ opacity: 0, y: 20 }}
            whileInView={{ opacity: 1, y: 0 }}
            transition={{ duration: 0.6 }}
            className="card-glass p-8 md:p-12 text-center space-y-6"
          >
            <h2 className="text-3xl md:text-4xl font-bold text-gradient">
              Ready to transform your meal planning?
            </h2>
            <p className="text-xl text-dark-300 max-w-2xl mx-auto">
              Join thousands of users who have revolutionized their approach to nutrition with AI-powered meal planning.
            </p>
            <Link 
              to="/register" 
              className="btn-primary text-lg px-8 py-4 inline-flex items-center hover-glow"
            >
              Get Started Today
            </Link>
          </motion.div>
        </div>
      </section>
    </div>
  );
};

export default LandingPage;